version: "3.9"
services:
  postgres:
    image: "postgres:14.5"
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  receipt:
    build: ./ReceiptAPI
    restart: always
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy